// Add Daiana's confirmed international WhatsApp number here (digits only).
const WHATSAPP_NUMBER = '59892347597';
const plans = [
{name:'Básico',price:'$4.800',description:'Para mantener tu marca activa y visualmente coherente.',items:['Portadas para historias destacadas','Optimización de la biografía','8 posteos mensuales','Diseño personalizado','Carruseles de hasta 7 placas','Ideas de contenido','Copy + CTA','Hashtags y palabras clave','Planificación mensual']},
{name:'Plus',price:'Precio a definir',description:'Más contenido y presencia durante toda la semana.',items:['Portadas para historias destacadas','Optimización de la biografía','8 posteos mensuales','3 Stories semanales','Diseño personalizado','Carruseles de hasta 7 placas','Ideas de contenido','Copy + CTA','Hashtags y palabras clave','Planificación mensual']},
{name:'Reels',price:'$5.500',description:'Contenido en video para darle movimiento y presencia a tu marca.',items:['Portadas para historias destacadas','Optimización de la biografía','8 Reels mensuales','Ideas y conceptos','Guión para cada Reel','Edición profesional','Textos, música y recursos visuales','Copy + CTA','Hashtags y palabras clave','Planificación mensual','Análisis básico de rendimiento']},
{name:'Completo',price:'$6.500',description:'Una propuesta que combina diseño y video de forma constante.',items:['Portadas para historias destacadas','Optimización de la biografía','8 posteos mensuales','4 Reels mensuales','Carruseles de hasta 7 placas','Diseño personalizado','Ideas y planificación','Guiones para Reels','Edición de video','Copy + CTA','Hashtags y palabras clave']}
];
document.querySelector('#plan-grid').innerHTML=plans.map(p=>`<article class="plan ${p.name==='Completo'?'featured':''}"><h3>${p.name}</h3><p class="plan-description">${p.description}</p><div class="price ${p.name==='Plus'?'pending':''}">${p.price}</div><div class="currency">${p.name==='Plus'?'CONSULTAME':'UYU / MES'}</div><ul>${p.items.map(i=>`<li>${i}</li>`).join('')}</ul><a class="button plan-contact" data-plan="${p.name}" href="#contacto">Consultar plan ${p.name} ↗</a></article>`).join('');
document.querySelector('#year').textContent=new Date().getFullYear();
if(WHATSAPP_NUMBER){document.querySelectorAll('a[href="#contacto"],#whatsapp').forEach(a=>{a.href=`https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(a.dataset.plan?`Hola Daiana, me interesa el plan ${a.dataset.plan}.`:'Hola Daiana, me gustaría hablar sobre las redes de mi marca.')}`;a.target='_blank';a.rel='noopener noreferrer'});document.querySelector('#contact-status').textContent='Contame qué tenés en mente.'}
let previous=window.scrollY,scheduled=false,paused=false;const reduced=matchMedia('(prefers-reduced-motion: reduce)');const nav=document.querySelector('#nav');const layers=document.querySelectorAll('[data-parallax]');
function render(){let y=window.scrollY;nav.classList.toggle('hidden',y>150&&y>previous&&!nav.contains(document.activeElement));previous=y;if(!reduced.matches&&!paused)layers.forEach(el=>{const r=el.parentElement.getBoundingClientRect();if(r.bottom>0&&r.top<innerHeight)el.style.transform=`translateY(${(innerHeight/2-r.top-r.height/2)*Number(el.dataset.parallax)}px)`});scheduled=false}
addEventListener('scroll',()=>{if(!scheduled){requestAnimationFrame(render);scheduled=true}},{passive:true});document.querySelector('#motion').addEventListener('click',e=>{paused=!paused;document.body.classList.toggle('paused',paused);e.currentTarget.setAttribute('aria-pressed',String(paused));e.currentTarget.textContent=paused?'Reanudar movimiento ▷':'Pausar movimiento Ⅱ';if(paused)layers.forEach(el=>el.style.transform='none')});
